[package]
name = "bevy_simple_tilemap"
version = "0.8.0"
authors = ["Forb.Jok <forbjok@gmail.com>"]
edition = "2021"
description = "Refreshingly simple tilemap implementation for Bevy Engine."
license = "MIT/Apache-2.0"
repository = "https://github.com/forbjok/bevy_simple_tilemap.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main" }
bitflags = "1.3.2"
bytemuck = "1.9.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1.5.3"
